### ==========================
###  methylclockData metadata
###  resources added in 2026
### ==========================

meta <- data.frame(
    Title = c("Coefficients DunedinPACE pace-of-aging estimator",
            "DunedinPACE reference means for probe normalization",
            "Coefficients NEOage post-menstrual age clock (450K)",
            "Coefficients NEOage post-menstrual age clock (EPIC)",
            "Coefficients NEOage post-natal age clock (450K)",
            "Coefficients NEOage post-natal age clock (EPIC)",
            "Coefficients Vidal-Bralo blood clock",
            "CpG set for the epiTOC1 mitotic counter",
            "CpG set for the HypoClock solo-WCGW counter",
            "CpG set for the stemTOC mitotic counter",
            "Coefficients CausAge causal clock",
            "Coefficients DamAge damaging causal clock",
            "Coefficients AdaptAge adaptive causal clock",
            "Coefficients Lin blood clock",
            "Coefficients Weidner three-CpG clock",
            "AltumAge input CpG order",
            "AltumAge neural network weights and scaler",
            "Coefficients McCartney smoking EpiScore",
            "Coefficients McCartney alcohol EpiScore",
            "Coefficients McCartney body mass index EpiScore",
            "Coefficients McCartney body fat EpiScore",
            "Coefficients McCartney education EpiScore",
            "Coefficients McCartney HDL cholesterol EpiScore",
            "Coefficients McCartney LDL cholesterol EpiScore",
            "Coefficients McCartney total cholesterol EpiScore",
            "Coefficients RepliTali mitotic clock",
            "Coefficients mCigarette smoking score",
            "Parameters for the epiTOC2 mitotic counter"),
    Description = c("173 CpGs described in Belsky (2022)",
                  "Reference probe means used to normalize the DunedinPACE input, from Belsky (2022)",
                  "408 CpGs described in Graw et al. (2021)",
                  "520 CpGs described in Graw et al. (2021)",
                  "302 CpGs described in Graw et al. (2021)",
                  "508 CpGs described in Graw et al. (2021)",
                  "8 CpGs described in Vidal-Bralo et al. (2016)",
                  "385 CpGs described in Yang et al. (2016)",
                  "678 CpGs described in Teschendorff (2020)",
                  "371 CpGs described in Zhu et al. (2024)",
                  "581 CpGs described in Ying et al. (2024)",
                  "1089 CpGs described in Ying et al. (2024)",
                  "998 CpGs described in Ying et al. (2024)",
                  "99 CpGs described in Lin et al. (2016)",
                  "3 CpGs described in Weidner et al. (2014)",
                  "The input CpG identifiers in the order the AltumAge network expects, from de Lima Camillo et al. (2022)",
                  "Layer weights and input scaler of the AltumAge neural network, from de Lima Camillo et al. (2022)",
                  "233 CpGs described in McCartney et al. (2018)",
                  "450 CpGs described in McCartney et al. (2018)",
                  "1109 CpGs described in McCartney et al. (2018)",
                  "968 CpGs described in McCartney et al. (2018)",
                  "373 CpGs described in McCartney et al. (2018)",
                  "737 CpGs described in McCartney et al. (2018)",
                  "233 CpGs described in McCartney et al. (2018)",
                  "204 CpGs described in McCartney et al. (2018)",
                  "87 CpGs described in Endicott et al. (2022)",
                  "1255 CpGs described in Chybowska et al. (2025)",
                  "163 CpGs described in Teschendorff (2020)"),
    BiocVersion = "3.24",
    Genome = "hg19",
    SourceType = c("RDA",
                 "RDA",
                 "RDA",
                 "RDA",
                 "RDA",
                 "RDA",
                 "RDA",
                 "RDA",
                 "RDA",
                 "RDA",
                 "RDA",
                 "RDA",
                 "RDA",
                 "RDA",
                 "RDA",
                 "RDA",
                 "HDF5",
                 "RDA",
                 "RDA",
                 "RDA",
                 "RDA",
                 "RDA",
                 "RDA",
                 "RDA",
                 "RDA",
                 "RDA",
                 "RDA",
                 "RDA"),
    SourceUrl = c("https://github.com/danbelsky/DunedinPACE",
                "https://github.com/danbelsky/DunedinPACE",
                "https://doi.org/10.18632/aging.203637",
                "https://doi.org/10.18632/aging.203637",
                "https://doi.org/10.18632/aging.203637",
                "https://doi.org/10.18632/aging.203637",
                "https://doi.org/10.3389/fgene.2016.00126",
                "https://github.com/aet21/EpiMitClocks",
                "https://github.com/aet21/EpiMitClocks",
                "https://github.com/aet21/EpiMitClocks",
                "https://github.com/bio-learn/biolearn",
                "https://github.com/bio-learn/biolearn",
                "https://github.com/bio-learn/biolearn",
                "https://doi.org/10.18632/aging.100908",
                "https://doi.org/10.1186/gb-2014-15-2-r24",
                "https://github.com/bio-learn/biolearn",
                "https://github.com/bio-learn/biolearn",
                "https://github.com/bio-learn/biolearn",
                "https://github.com/bio-learn/biolearn",
                "https://github.com/bio-learn/biolearn",
                "https://github.com/bio-learn/biolearn",
                "https://github.com/bio-learn/biolearn",
                "https://github.com/bio-learn/biolearn",
                "https://github.com/bio-learn/biolearn",
                "https://github.com/bio-learn/biolearn",
                "https://github.com/aet21/EpiMitClocks",
                "https://github.com/aleksandra-chybowska/Smoking_EpiScore",
                "https://github.com/aet21/EpiMitClocks"),
    SourceVersion = "August 2026",
    Species = "Homo sapiens",
    TaxonomyId = 9606,
    Coordinate_1_based = FALSE,
    DataProvider = NA,
    Maintainer = "Dolors Pelegri-Siso <dolors.pelegri@isglobal.org>",
    RDataClass = c("data.frame",
                 "data.frame",
                 "data.frame",
                 "data.frame",
                 "data.frame",
                 "data.frame",
                 "data.frame",
                 "data.frame",
                 "data.frame",
                 "data.frame",
                 "data.frame",
                 "data.frame",
                 "data.frame",
                 "data.frame",
                 "data.frame",
                 "character",
                 "character",
                 "data.frame",
                 "data.frame",
                 "data.frame",
                 "data.frame",
                 "data.frame",
                 "data.frame",
                 "data.frame",
                 "data.frame",
                 "data.frame",
                 "data.frame",
                 "data.frame"),
    DispatchClass = c("Rda",
                    "Rda",
                    "Rda",
                    "Rda",
                    "Rda",
                    "Rda",
                    "Rda",
                    "Rda",
                    "Rda",
                    "Rda",
                    "Rda",
                    "Rda",
                    "Rda",
                    "Rda",
                    "Rda",
                    "Rda",
                    "FilePath",
                    "Rda",
                    "Rda",
                    "Rda",
                    "Rda",
                    "Rda",
                    "Rda",
                    "Rda",
                    "Rda",
                    "Rda",
                    "Rda",
                    "Rda"),
    Location_Prefix = "https://zenodo.org/records/21840402/files/",
    RDataPath = c("coefDunedinPACE.rda",
                "coefDunedinPACEGS.rda",
                "coefNEOaPMA450K.rda",
                "coefNEOaPMAEPIC.rda",
                "coefNEOaPNA450K.rda",
                "coefNEOaPNAEPIC.rda",
                "coefVidalBralo.rda",
                "coefEpiTOC1.rda",
                "coefHypoClock.rda",
                "coefStemTOC.rda",
                "coefCausAge.rda",
                "coefDamAge.rda",
                "coefAdaptAge.rda",
                "coefLin.rda",
                "coefWeidner.rda",
                "coefAltumAgeRef.rda",
                "coefAltumAge.hdf5",
                "coefMcCartneySmoking.rda",
                "coefMcCartneyAlcohol.rda",
                "coefMcCartneyBMI.rda",
                "coefMcCartneyBodyFat.rda",
                "coefMcCartneyEducation.rda",
                "coefMcCartneyHDL.rda",
                "coefMcCartneyLDL.rda",
                "coefMcCartneyTotalChol.rda",
                "coefRepliTali.rda",
                "coefMcCigarette.rda",
                "coefEpiTOC2.rda"),
    Tags = "methylclock:DNAmAge:EpigeneticClock:DNAMethylation",
    stringsAsFactors = FALSE
)

write.csv(meta, file = "inst/extdata/metadata_v2026_08.csv",
          row.names = FALSE)
